ALIASES_COLUNAS = {
    "Matem": "Mat",
    "Portug": "Por",
    "Inglês": "Ing",
    "Fase ideal": "Fase Ideal",
    "Defas": "Defasagem",
    "Nome Anonimizado": "Nome",
    "INDE 23": "INDE 2023",
    "INDE 22": "INDE 2022",
}

COLUNAS_NUMERICAS = [
    "Idade",
    "Ano nasc",
    "Ano ingresso",
    "INDE 2022",
    "INDE 2023",
    "INDE 2024",
    "IAA",
    "IEG",
    "IPS",
    "IPP",
    "IDA",
    "IPV",
    "IAN",
    "Mat",
    "Por",
    "Ing",
    "Defasagem",
]

COLUNAS_CATEGORICAS = [
    "Fase",
    "Turma",
    "Gênero",
    "Instituição de ensino",
    "Fase Ideal",
    "Pedra 2020",
    "Pedra 2021",
    "Pedra 2022",
    "Pedra 2023",
    "Pedra 2024",
    "Indicado",
    "Atingiu PV",
    "Ativo/ Inativo",
]

COLUNAS_SAIDA_ORDENADA = [
    "RA",
    "Nome",
    "Gênero",
    "Turma",
    "Escola",
    "Instituição de ensino",
    "Ativo/ Inativo",
    "Ano ingresso",
    "Fase",
    "Fase Ideal",
    "Defasagem",
    "Pedra 2020",
    "Pedra 2021",
    "Pedra 2022",
    "Pedra 2023",
    "Pedra 2024",
    "INDE 2022",
    "INDE 2023",
    "INDE 2024",
]